services:
  ikb-energy-scraper:
    image: ghcr.io/philippthaler/ikb-energy-scraper:latest
    container_name: ikb-energy-scraper
    restart: unless-stopped
    # env_file: .env
    environment:
      IKB_USERNAME: meine_email@beispiel.at
      IKB_PASSWORD: mein_passwort123
    volumes:
      - ./data:/data
    # Run in daemon mode, scraping every day at 01:00 AM
    command: [ "--schedule", "01:00", "--log-level", "INFO" ]
